import { useState, useEffect, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Newspaper, Book, Clock, Search, Gavel, 
  AlertCircle, RefreshCw, ShieldCheck, Info,
  Camera, ArrowLeft
} from 'lucide-react';
import { NewsCard } from '../components/Intelligence/NewsCard';
import { GlossaryItem } from '../components/Intelligence/GlossaryItem';
import { ProcedureWalkthrough } from '../components/Intelligence/ProcedureWalkthrough';
import { LiteracyCard } from '../components/Intelligence/LiteracyCard';
import { HighlightCard } from '../components/Intelligence/HighlightCard';
import { CategorySidebar } from '../components/Intelligence/CategorySidebar';
import { ViolationChecker } from '../components/Intelligence/ViolationChecker';
import { LegalBlueprint } from '../components/Intelligence/LegalBlueprint';
import { ResourceDirectory } from '../components/Intelligence/ResourceDirectory';
import { FULL_GLOSSARY } from '../data/legalGlossary';
import { PROCEDURAL_GUIDES, LIMITATION_PERIODS } from '../data/legalProcedures';
import { LEGAL_LITERACY_DATA, DID_YOU_KNOW_FACTS } from '../data/legalLiteracy';
import { CONFIG } from '../config';
import styles from '../components/Intelligence/Intelligence.module.css';

export default function IntelligenceHub() {
  const [activeTab, setActiveTab] = useState<'news' | 'glossary' | 'procedures' | 'rights'>('news');
  const [activeCategory, setActiveCategory] = useState('all');
  const [news, setNews] = useState<any[]>([]);
  const [loadingNews, setLoadingNews] = useState(true);
  const [newsError, setNewsError] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [dailyFact, setDailyFact] = useState('');
  const [screenshotMode, setScreenshotMode] = useState(false);

  const fetchNews = async () => {
    setLoadingNews(true);
    setNewsError(false);
    try {
      const resp = await fetch(`${CONFIG.API_URL}/api/news`);
      if (!resp.ok) throw new Error('Source offline');
      const data = await resp.json();
      setNews(data);
    } catch (e) {
      console.error('Failed to load news wire');
      setNewsError(true);
    } finally {
      setLoadingNews(false);
    }
  };

  useEffect(() => {
    fetchNews();
    const randomFact = DID_YOU_KNOW_FACTS[Math.floor(Math.random() * DID_YOU_KNOW_FACTS.length)];
    setDailyFact(randomFact);
  }, []);

  const filteredGlossary = useMemo(() => {
    if (!searchQuery) return FULL_GLOSSARY;
    const q = searchQuery.toLowerCase();
    return FULL_GLOSSARY.filter(item => 
      item.term.toLowerCase().includes(q) ||
      item.definition.toLowerCase().includes(q)
    );
  }, [searchQuery]);

  const filteredLiteracy = useMemo(() => {
    let base = LEGAL_LITERACY_DATA;
    if (activeCategory !== 'all') {
      base = base.filter(item => item.category === activeCategory);
    }
    if (!searchQuery) return base;
    const q = searchQuery.toLowerCase();
    return base.filter(item => 
      item.title.toLowerCase().includes(q) ||
      item.summary.toLowerCase().includes(q)
    );
  }, [searchQuery, activeCategory]);

  if (screenshotMode) {
    return (
      <div className={styles.screenshotView}>
        <button onClick={() => setScreenshotMode(false)} className={styles.backBtn}>
          <ArrowLeft size={20} /> Exit Screenshot Mode
        </button>
        <div className={styles.screenshotContent}>
          <div className={styles.screenshotHeader}>
            <ShieldCheck size={40} color="var(--color-accent)" />
            <h1>Essential Citizen Rights</h1>
            <p>Know Your Law, Protect Your Liberty.</p>
          </div>
          <div className={styles.screenshotGrid}>
            {LEGAL_LITERACY_DATA.slice(0, 6).map(guide => (
              <div key={guide.id} className={styles.miniGuide}>
                <h4>{guide.title}</h4>
                <p>{guide.summary}</p>
              </div>
            ))}
          </div>
          <footer className={styles.screenshotFooter}>
            Generated by LegalSaathi Hub | EMERGENCY: 1930 (Cyber) | 1091 (Women)
          </footer>
        </div>
      </div>
    );
  }

  return (
    <div className={styles.hubWrapper}>
      <header className={styles.hubHeader}>
        <motion.h1 
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
        >
          Intelligence Hub
        </motion.h1>
        <p>Expert-level insights, citizens' rights, and real-time legal intelligence.</p>
      </header>

      <div style={{ display: 'flex', gap: '8px', justifyContent: 'center', marginBottom: '40px', flexWrap: 'wrap' }}>
        {[
          { id: 'news', label: 'News Wire', icon: <Newspaper size={18} /> },
          { id: 'rights', label: 'Combat Kit', icon: <ShieldCheck size={18} /> },
          { id: 'procedures', label: 'When/Where/How', icon: <Gavel size={18} /> },
          { id: 'glossary', label: 'Glossary', icon: <Book size={18} /> }
        ].map(tab => (
          <button
            key={tab.id}
            className={`btn-${activeTab === tab.id ? 'accent' : 'outlined'}`}
            onClick={() => {
              setActiveTab(tab.id as any);
              setSearchQuery('');
              window.scrollTo({ top: 0, behavior: 'smooth' });
            }}
            style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 20px', borderRadius: '12px', fontSize: '0.9rem' }}
          >
            {tab.icon} {tab.label}
          </button>
        ))}
      </div>

      <AnimatePresence mode="wait">
        {activeTab === 'news' && (
          <motion.div 
            key="news"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className={styles.grid}
          >
            <div className={styles.section}>
              <div className={styles.sectionHeader}>
                <h2><Newspaper /> Legal News Wire</h2>
                <div className="badge badge-accent">LIVE</div>
              </div>
              
              <HighlightCard type="fact" content={dailyFact} />

              {loadingNews ? (
                <div style={{ display: 'flex', justifyContent: 'center', padding: '60px' }}>
                  <div className="loader" />
                </div>
              ) : newsError ? (
                <div className={styles.errorState}>
                  <AlertCircle size={48} color="#EF4444" style={{ marginBottom: '16px' }} />
                  <h3>Primary Fetch Offline</h3>
                  <button className="btn-outlined" onClick={fetchNews}><RefreshCw size={16} /> Tap to Retry</button>
                </div>
              ) : (
                <div className={styles.newsGrid}>
                  {news.map((item, i) => (
                    <NewsCard 
                      key={i}
                      title={item.title}
                      source={item.source}
                      date={item.pubDate}
                      link={item.link}
                      snippet={item.contentSnippet}
                    />
                  ))}
                </div>
              )}
            </div>

            <aside>
              <div className={styles.section}>
                <h2><Info /> Contextual Alerts</h2>
                <div style={{ padding: '16px', background: 'rgba(59, 130, 246, 0.05)', borderRadius: '16px', borderLeft: '4px solid var(--color-accent)' }}>
                  <h4 style={{ margin: '0 0 8px 0', fontSize: '0.9rem' }}>Supreme Court Update</h4>
                  <p style={{ margin: 0, fontSize: '0.8rem', opacity: 0.7 }}>Constitutional Bench to hear key citizenship petitions tomorrow at 10:30 AM.</p>
                </div>
              </div>
            </aside>
          </motion.div>
        )}

        {activeTab === 'rights' && (
          <motion.div 
            key="rights"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
          >
            <ViolationChecker />

            <div className={styles.grid}>
              <section className={styles.section}>
                <div className={styles.sectionHeader}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                    <h2><ShieldCheck /> Citizens' Rights Library</h2>
                    <button 
                      onClick={() => setScreenshotMode(true)} 
                      className={styles.captureBtn}
                      title="Export simplified rights for mobile"
                    >
                      <Camera size={18} />
                    </button>
                  </div>
                  <div className="badge badge-outlined">{filteredLiteracy.length} Articles</div>
                </div>

                <div style={{ position: 'relative', marginBottom: '32px' }}>
                  <Search style={{ position: 'absolute', left: '16px', top: '50%', transform: 'translateY(-50%)', opacity: 0.4 }} size={20} />
                  <input 
                    type="text" 
                    placeholder="Search rights & remedies..."
                    className={styles.searchBar}
                    style={{ paddingLeft: '52px' }}
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                  />
                </div>

                <div className={styles.hubLayout}>
                  <CategorySidebar 
                    activeCategory={activeCategory} 
                    onSelect={setActiveCategory} 
                  />
                  
                  <div className={styles.literacyGrid}>
                    {filteredLiteracy.length > 0 ? (
                      filteredLiteracy.map(guide => (
                        <LiteracyCard 
                          key={guide.id}
                          title={guide.title}
                          category={guide.category}
                          summary={guide.summary}
                          content={guide.content}
                          mythBusters={guide.mythBusters}
                          templates={guide.templates}
                        />
                      ))
                    ) : (
                      <div className={styles.emptyState}>
                        <Book size={48} opacity={0.2} />
                        <p>No guides found in this category.</p>
                      </div>
                    )}
                  </div>
                </div>
              </section>

              <aside>
                <LegalBlueprint />
                <ResourceDirectory />
              </aside>
            </div>
          </motion.div>
        )}

        {activeTab === 'procedures' && (
          <motion.div 
            key="procedures"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className={styles.grid}
          >
            <div className={styles.section}>
              <div className={styles.sectionHeader}>
                <h2><Gavel /> When, Where & How</h2>
              </div>
              {PROCEDURAL_GUIDES.map(guide => (
                <ProcedureWalkthrough 
                  key={guide.id}
                  title={guide.title}
                  description={guide.description}
                  steps={guide.steps}
                />
              ))}
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
              <div className={styles.section}>
                <h3><Clock /> Limitation Deadlines</h3>
                <div className={styles.tableContainer}>
                  <table className={styles.table}>
                    <thead>
                      <tr><th>Suit Type</th><th>Period</th></tr>
                    </thead>
                    <tbody>
                      {LIMITATION_PERIODS.map((lp, i) => (
                        <tr key={i}><td>{lp.suit}</td><td style={{ fontWeight: 600, color: 'var(--color-accent)' }}>{lp.period}</td></tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </motion.div>
        )}

        {activeTab === 'glossary' && (
          <motion.div 
            key="glossary"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className={styles.section}
          >
            <div className={styles.sectionHeader}>
              <h2><Book /> Legal Glossary</h2>
            </div>

            <div style={{ position: 'relative', marginBottom: '32px' }}>
              <Search style={{ position: 'absolute', left: '16px', top: '50%', transform: 'translateY(-50%)', opacity: 0.4 }} size={20} />
              <input 
                type="text" 
                placeholder="Search 200+ terms..."
                className={styles.searchBar}
                style={{ paddingLeft: '52px' }}
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '16px' }}>
              {filteredGlossary.slice(0, 100).map((term, i) => (
                <GlossaryItem key={i} term={term.term} definition={term.definition} category={term.category} />
              ))}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
